version: "3"

services:
  frontend:
    build: ./ml-kurkkumopo-frontend
    ports: 
      - 3000:3000
    container_name: machine_learning_frontend

  backend:
    build: ./ml-kurkkumopo-backend
    ports: 
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: machine_learning_backend

  training:
    build: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - imgs:/src/imgs
    container_name: machine_learning_training

volumes:
  model:
  imgs:
