version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - backbone

  front-end:
    depends_on:
      - nginx
    build: ../material-applications/example-frontend/
    ports:
      - 5000:5000
    container_name: front-end
    networks:
      - backbone

  back-end:
    depends_on:
      - nginx
    build: ../material-applications/example-backend/
    environment:
      - REDIS_HOST=redis-container
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PASSWORD=example
    ports:
      - 8080:8080
    container_name: back-end
    networks:
      - backbone
  
  redis:
    image: redis
    container_name: redis-container
    networks:
      - backbone

  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    container_name: postgres-db
    networks:
      - backbone

networks:
  backbone:
    driver: bridge
